### ISSUE TITLE
Cannot install module

### ISSUE THREAD

**Issue by stonedtroll** [smeevil/foundryvtt-movement-approval#1]
Getting the following error:

Metadata validation failed for module "movement-approval": The file "movement-approval.js" included by module movement-approval does not exist

**Comment by stonedtroll** [comment]
Also...1st!

**Comment by Arcainne** [comment]
I'm also getting that error. Also, downloading the zip file doesn't include the module.

**Comment by smeevil** [comment]
Hi, thanks for bringing that to notice. There was a misconfiguration in the github action creating the package. That has been fixed now :) Could you please try again?

**Comment by stonedtroll** [comment]
Resolved. Thank you!
